version: '3.9'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    extra_hosts:
      - "narourb:172.18.0.15"
      - "host.docker.internal:host-gateway"
    ports:
      - "443:443"
    environment:
      TS_ADMIN_KEY: ${TS_ADMIN_KEY}
      TAILNET_NAME: ${TAILNET_NAME}
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: ${TS_HOSTNAME}
      TZ: ${TZ}
    volumes:
      - /dev/net/tun:/dev/net/tun
      - nginx-tailscale:/var/lib/tailscale
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl
      - webnovel:/usr/share/nginx/html:ro    # ← 変更
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  narourb:
    build: ./narourb
    container_name: narourb
    stdin_open: false   # TTY不要ならオフのままでOK
    tty: false
    depends_on:
     - nginx
    # ↓ ここだけを変更
    network_mode: "container:nginx"
    environment:
      TZ: ${TZ}
    volumes:
      - webnovel:/share/data             # ← 変更
      - ./files/webnovel:/files/webnovel:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  rclone-backup:
    build: ./rclone
    container_name: rclone-backup
    depends_on:
      - narourb
    networks:
      - backend
    environment:
      WEBDAV_URL:         ${WEBDAV_URL}
      WEBDAV_PATH:        ${WEBDAV_PATH}
      WEBDAV_USER:        ${WEBDAV_USER}
      WEBDAV_PASS:        ${WEBDAV_PASS}
      WEBDAV_VENDOR:      ${WEBDAV_VENDOR}
      WEBDAV_REMOTE_NAME: ${WEBDAV_REMOTE_NAME}
      TZ: ${TZ}
    volumes:
      - webnovel:/share/data               # ← 変更
      - rclone-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  nginx-tailscale:
  webnovel:       # ← ここを追加（旧 shared-data を webnovel に）
  rclone-config:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16