services:

  narou_rb_tailscale:
    build: ./tailscale
    container_name: narou_rb_tailscale
    command: ["/entrypoint.sh"]
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /dev/net/tun:/dev/net/tun
      - narou_rb-tailscale:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_ADMIN_KEY: ${TS_ADMIN_KEY}
      TAILNET_NAME: ${TAILNET_NAME}
      TS_HOSTNAME: ${TS_HOSTNAME}

  nginx:
    build: ./nginx
    container_name: narou_rb_nginx
    network_mode: "service:narou_rb_tailscale"
    depends_on:
      - narou_rb_tailscale
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl
      - webnovel:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  narou_rb:
    build: ./narou_rb
    container_name: narou_rb
    network_mode: "service:narou_rb_tailscale"
    depends_on:
      - narou_rb_tailscale
    restart: always
    environment:
      TZ: ${TZ}
      NO_CONVERT_EPUB: ${NO_CONVERT_EPUB}
      AUTO_ADD_TAG: ${AUTO_ADD_TAG}
      AUTO_UPDATE: ${AUTO_UPDATE}
      AUTO_UPDATE_TIME: ${AUTO_UPDATE_TIME}
      AUTO_DIGEST_OPTIONS: ${AUTO_DIGEST_OPTIONS}
    volumes:
      - webnovel:/share/data
      - epub:/share/epub
      - ./files/webnovel:/files/webnovel:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  rclone-backup:
    build: ./rclone
    container_name: narou_rb_rclone-backup
    depends_on:
      - narou_rb
    networks:
      - backend
    environment:
      WEBDAV_URL:         ${WEBDAV_URL}
      WEBDAV_PATH:        ${WEBDAV_PATH}
      WEBDAV_USER:        ${WEBDAV_USER}
      WEBDAV_PASS:        ${WEBDAV_PASS}
      WEBDAV_VENDOR:      ${WEBDAV_VENDOR}
      WEBDAV_REMOTE_NAME: ${WEBDAV_REMOTE_NAME}
      EPUB_REMOTE: ${EPUB_REMOTE}
      TZ: ${TZ}
    volumes:
      - webnovel:/share/data
      - epub:/share/epub
      - rclone-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  narou_rb-tailscale:
  webnovel:
  epub:
  rclone-config:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16